apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: applications
  labels:
    app: backend-api
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: backend-api
