apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: applications
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: tauqeerahmad104/webapi:latest
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              value: "server=mysql.infrastructure.svc.cluster.local;database=webappdb;user=webappuser;password=webappuser"
