apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: applications
  labels:
    app: backend-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  selector:
    app: backend-api
