apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: applications
  labels:
    app: frontend-app
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  selector:
    app: frontend-app
