apiVersion: v2
name: infra-chart
description: "Infra: MySQL and backups"
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: mysql
    version: "12.1.0"
    repository: "https://charts.bitnami.com/bitnami"