mysql:
  image:
    repository: mysql
    tag: "8.0"

  auth:
    rootPassword: "root123"
    username: "webappuser"
    password: "webappuser"
    database: "webappdb"

  pvc:
    name: mysql-data-pvc
    size: 1Gi
    storageClass: local-path

backup:
  enabled: true
  schedule: "*/5 * * * *"   # every 5 minutes (demo)
  pvc:
    name: "mysql-backup-pvc"
    size: "1Gi"
    storageClass: "local-path"
