mysql:
  image:
    repository: mysql
    tag: "8.0"

  auth:
    rootPassword: "root123"
    username: "webappuser"
    password: "webappuser"
    database: "webappdb"

  pvc:
    name: mysql-data-pvc
    size: 1Gi
    storageClass: local-path

backup:
  enabled: true
  name: mysql-backup
  image: mysql:8
  schedule: "*/5 * * * *"   # every 5 minutes
  pvc:
    name: mysql-backup-pvc
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: local-path
