{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.backup.name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mysql-backup
              image: {{ .Values.backup.image }}
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-root-secret
                      key: password
              command:
                - sh
                - -c
                - |
                  mysqldump -h mysql -u root --all-databases > /backup/db-$(date +%F-%H-%M).sql
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: {{ .Values.backup.pvc.name }}
{{- end }}
